; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./

[env:genericSTM32F103C8]
platform = ststm32
; board = custom_STM32F407IGT6 
board = genericSTM32F103C8 
build_flags = 
	-I Inc
	-I Drivers/STM32F1xx_HAL_Driver/Inc
	-I Drivers/STM32F1xx_HAL_Driver/Inc/Legacy
	-I Drivers/CMSIS/Device/ST/STM32F1xx/Include
	-I Drivers/CMSIS/Include
	-I Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
	-I Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
	-I Middlewares/Third_Party/FreeRTOS/Source/include
build_src_filter = +<Src/> +<startup_stm32f103xb.s> +<Drivers/> +<Middlewares/>
board_build.ldscript = ./STM32F103XX_FLASH.ld
; extra_scripts = pre:hardfloat.py
upload_protocol = stlink